#%RAML 1.0 NamedExample
value:
  password: admin
  user:  admin
  accountNum: "1234567890"
  bank: HDFC
  acctStatus:  Lock
   





# example:
#   {
      
#     "password": admin ,
#     "user": admin ,
#     "accountNum": "1234567895" ,
#     "bank": "HDFC" ,
#     "acctStatus": "Lock"
  
#   }
  