http:
  port: "8081"

snowDb:
  accountName: "BZAXLZZ-BJ08531"
  warehouse: "COMPUTE_WH"
  database: "VITECH"
  schema: "BFS"
  user: "Alchemist17"
  password: "A9284799919@chim"
  role: "ACCOUNTADMIN" 

#${db.sfc.accountName} 

email:
  host: "smtp.gmail.com" 
  user: "bharatchim17@gmail.com" 
  password: "uqyc dtoi doss dvst" 
  port: "587"
  
#${email.user}
